# vim: ts=2:sts=2:sw=2:expandtab:smarttab:

pipeline:
  build:
    image: golang
    commands:
      - export GOPATH=$(pwd)
      - cd src/fuse
      - go get
      - go build

  test:
    image: golang
    commands:
      - export GOPATH=$(pwd)
      - cd src/fuse
      - go test

  publish-docker:
    image: plugins/docker
    tag:
      - latest
    repo: ontrif/fuse
    when:
      branch: master
    secrets: [ docker_username, docker_password ]

  publish-docker:
    image: plugins/docker
    tag:
      - ${DRONE_TAG}
    repo: ontrif/fuse
    when:
      event: tag
    secrets: [ docker_username, docker_password ]
