# vim: ts=2:sts=2:sw=2:expandtab:smarttab:

pipeline:
  build:
    image: golang
    commands:
      - go test fuse/pkg/domain
      - go build -o bin/fuse -ldflags "-X fuse/pkg/config.AppVersion=${DRONE_TAG=dev-build}" cmd/fuse/main.go


  publish-docker:
    image: plugins/docker
    tag:
      - latest
    repo: ontrif/fuse
    when:
      branch: master
    secrets: [ docker_username, docker_password ]

  publish-docker:
    image: plugins/docker
    tag:
      - ${DRONE_TAG}
    repo: ontrif/fuse
    when:
      event: tag
    secrets: [ docker_username, docker_password ]
